# folders which be build during the bulding process
# they are name free
LIB_dir =  $(shell pwd)/lib

# extern lib
INC_BOOST = /usr/local/Cellar/boost/1.73.0/include
INC_FFTW  = /usr/local/Cellar/fftw/3.3.8_2/include/
LIB_FFTW  = fftw3

# compiler
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Linux)
	CXX = g++ -std=c++1z
	echo = echo -e
endif
ifeq ($(UNAME_S),Darwin)
	CXX = g++-10 -std=c++17
endif

#CXX = clang++
#CFLAGS = -std=c++1y -stdlib=libc++   

# if you want to switch compiler : make switch COMPILER=g++
#CXX = g++-10 -std=c++17
#CXX = g++ -std=c++1z
#CXX = clang++ -std=c++1y -stdlib=libc++
#CXX = scan-build -v -k --force-analyze-debug-code -o html clang++ -std=c++1y -stdlib=libc++
