#autogenerate by ./install.sh (2017-07-18)

# folders which be build during the bulding process
# they are name free
LIB_dir =  $(shell pwd)/lib

# extern lib
INC_BOOST = /usr/local/Cellar/boost/1.72.0_3/include
INC_FFTW  = /usr/local/Cellar/fftw/3.3.8_2/include/
LIB_FFTW  = fftw3

# compiler
#CXX = clang++
#CFLAGS = -std=c++1y -stdlib=libc++   

# if you want to switch compiler : make switch COMPILER=g++
CXX = g++-10 -std=c++17
#CXX = g++ -std=c++1z
#CXX = clang++ -std=c++1y -stdlib=libc++
#CXX = scan-build -v -k --force-analyze-debug-code -o html clang++ -std=c++1y -stdlib=libc++
