# folders which be build during the bulding process
# they are name free
LIB_dir =  $(shell pwd)/lib

# extern lib
INC_BOOST = /usr/local/Cellar/boost/1.75.0_1/include
INC_FFTW  = /usr/local/Cellar/fftw/3.3.9/include/
LIB_FFTW  = fftw3

# compiler
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S),Linux)
	CXX = g++ -std=c++1z
	echo = echo -e
endif
ifeq ($(UNAME_S),Darwin)
	CXX = g++-10 -std=c++17
	#CXX = /usr/local/Cellar/llvm/11.0.0/bin/clang++ -std=c++17
	#LDFLAGS=-L$(brew --prefix)/opt/llvm/lib -Wl,-rpath,$(brew --prefix)/opt/llvm/lib
endif


# JC_condition make (jc_x,jc_y) equals to zero at each time if it sets to 0
JC_condition := 1
# Bxy_condition make (B_x,B_y) equals to zero at each time if it sets to 0
Bxy_condition := 1
# Bxy_condition make (B_x,B_y) equals to zero at each time if it sets to 0
Exy_condition := 1

# for Vlasov-Maxwell JC_condition = 0, Bxy_condition = 1
# for Vlasov-Ampère  JC_condition = 0, Bxy_condition = 0


#CXX = clang++
#CFLAGS = -std=c++1y -stdlib=libc++   

#CXX = g++-10 -std=c++17
#CXX = g++ -std=c++1z
#CXX = clang++ -std=c++1y -stdlib=libc++
#CXX = scan-build -v -k --force-analyze-debug-code -o html clang++ -std=c++1y -stdlib=libc++
